// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.roo.torrus.client.managed.request;

import ch.unibas.roo.torrus.client.request.SettingsRequest;
import ch.unibas.roo.torrus.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    SettingsRequest settingsRequest();
}
