// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.roo.torrus.client.managed.activity;

import ch.unibas.roo.torrus.client.managed.request.ApplicationRequestFactory;
import ch.unibas.roo.torrus.client.proxy.DeviceProxy;
import ch.unibas.roo.torrus.client.scaffold.ScaffoldMobileApp;
import ch.unibas.roo.torrus.client.scaffold.activity.IsScaffoldMobileActivity;
import ch.unibas.roo.torrus.client.scaffold.place.AbstractProxyListActivity;
import ch.unibas.roo.torrus.client.scaffold.place.ProxyListView;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.gwt.view.client.Range;
import com.google.web.bindery.requestfactory.shared.Receiver;
import com.google.web.bindery.requestfactory.shared.Request;
import java.util.List;

public abstract class DeviceListActivity_Roo_Gwt extends AbstractProxyListActivity<DeviceProxy> implements IsScaffoldMobileActivity {

    protected ApplicationRequestFactory requests;

    public DeviceListActivity_Roo_Gwt(PlaceController placeController, ProxyListView<ch.unibas.roo.torrus.client.proxy.DeviceProxy> view, Class<ch.unibas.roo.torrus.client.proxy.DeviceProxy> proxyType) {
        super(placeController, view, proxyType);
    }

    protected void fireCountRequest(Receiver<java.lang.Long> callback) {
        requests.deviceRequest().countDevices().fire(callback);
    }
}
