// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.roo.torrus.client.managed.activity;

import ch.unibas.roo.torrus.client.managed.request.ApplicationRequestFactory;
import ch.unibas.roo.torrus.client.managed.ui.SettingsDetailsView;
import ch.unibas.roo.torrus.client.managed.ui.SettingsEditView;
import ch.unibas.roo.torrus.client.managed.ui.SettingsListView;
import ch.unibas.roo.torrus.client.managed.ui.SettingsMobileDetailsView;
import ch.unibas.roo.torrus.client.managed.ui.SettingsMobileEditView;
import ch.unibas.roo.torrus.client.proxy.SettingsProxy;
import ch.unibas.roo.torrus.client.request.SettingsRequest;
import ch.unibas.roo.torrus.client.scaffold.ScaffoldApp;
import ch.unibas.roo.torrus.client.scaffold.place.CreateAndEditProxy;
import ch.unibas.roo.torrus.client.scaffold.place.FindAndEditProxy;
import ch.unibas.roo.torrus.client.scaffold.place.ProxyPlace;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;

public abstract class SettingsActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        SettingsEditView.instance().setCreating(true);
        final SettingsRequest request = requests.settingsRequest();
        Activity activity = new CreateAndEditProxy<SettingsProxy>(SettingsProxy.class, request, ScaffoldApp.isMobile() ? SettingsMobileEditView.instance() : SettingsEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SettingsProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new SettingsEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SettingsMobileEditView.instance() : SettingsEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<ch.unibas.roo.torrus.client.proxy.SettingsProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<SettingsProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        SettingsEditView.instance().setCreating(false);
        EntityProxyId<SettingsProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<SettingsProxy>(proxyId, requests, ScaffoldApp.isMobile() ? SettingsMobileEditView.instance() : SettingsEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(SettingsProxy proxy) {
                SettingsRequest request = requests.settingsRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new SettingsEditActivityWrapper(requests, ScaffoldApp.isMobile() ? SettingsMobileEditView.instance() : SettingsEditView.instance(), activity, proxyId);
    }
}
