// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package ch.unibas.roo.torrus.client.managed.ui;

import ch.unibas.roo.torrus.client.managed.request.ApplicationEntityTypesProcessor;
import ch.unibas.roo.torrus.client.proxy.DeviceProxy;
import ch.unibas.roo.torrus.client.proxy.SettingsProxy;
import ch.unibas.roo.torrus.client.scaffold.place.ProxyListPlace;
import com.google.gwt.text.shared.AbstractRenderer;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleDevice(DeviceProxy isNull) {
                setResult("Devices");
            }

            @Override
            public void handleSettings(SettingsProxy isNull) {
                setResult("Settingss");
            }
        }.process(object.getProxyClass());
    }
}
