// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.roo.torrus.server.domain;

import ch.unibas.roo.torrus.server.domain.Device;

privileged aspect Device_Roo_JavaBean {
    
    public String Device.getName() {
        return this.name;
    }
    
    public void Device.setName(String name) {
        this.name = name;
    }
    
}
