// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.roo.torrus.server.domain;

import ch.unibas.roo.torrus.server.domain.Settings;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Settings_Roo_Configurable {
    
    declare @type: Settings: @Configurable;
    
}
