// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.unibas.roo.torrus.server.domain;

import ch.unibas.roo.torrus.server.domain.Settings;
import ch.unibas.roo.torrus.server.domain.SettingsDataOnDemand;
import ch.unibas.roo.torrus.server.domain.SettingsIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SettingsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SettingsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SettingsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SettingsIntegrationTest: @Transactional;
    
    @Autowired
    private SettingsDataOnDemand SettingsIntegrationTest.dod;
    
    @Test
    public void SettingsIntegrationTest.testCountSettingses() {
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", dod.getRandomSettings());
        long count = Settings.countSettingses();
        Assert.assertTrue("Counter for 'Settings' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SettingsIntegrationTest.testFindSettings() {
        Settings obj = dod.getRandomSettings();
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Settings' failed to provide an identifier", id);
        obj = Settings.findSettings(id);
        Assert.assertNotNull("Find method for 'Settings' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Settings' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SettingsIntegrationTest.testFindAllSettingses() {
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", dod.getRandomSettings());
        long count = Settings.countSettingses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Settings', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Settings> result = Settings.findAllSettingses();
        Assert.assertNotNull("Find all method for 'Settings' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Settings' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SettingsIntegrationTest.testFindSettingsEntries() {
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", dod.getRandomSettings());
        long count = Settings.countSettingses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Settings> result = Settings.findSettingsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Settings' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Settings' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SettingsIntegrationTest.testFlush() {
        Settings obj = dod.getRandomSettings();
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Settings' failed to provide an identifier", id);
        obj = Settings.findSettings(id);
        Assert.assertNotNull("Find method for 'Settings' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySettings(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Settings' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SettingsIntegrationTest.testMergeUpdate() {
        Settings obj = dod.getRandomSettings();
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Settings' failed to provide an identifier", id);
        obj = Settings.findSettings(id);
        boolean modified =  dod.modifySettings(obj);
        Integer currentVersion = obj.getVersion();
        Settings merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Settings' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SettingsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", dod.getRandomSettings());
        Settings obj = dod.getNewTransientSettings(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Settings' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Settings' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Settings' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SettingsIntegrationTest.testRemove() {
        Settings obj = dod.getRandomSettings();
        Assert.assertNotNull("Data on demand for 'Settings' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Settings' failed to provide an identifier", id);
        obj = Settings.findSettings(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Settings' with identifier '" + id + "'", Settings.findSettings(id));
    }
    
}
